### ISSUE TITLE
Use your own layout

### ISSUE THREAD

**Issue by accessd** [smathieu/prosperity#47]
Hi!
How about in order to give the possibility to use your own layout? With the ability to insert links on Dashboards and Browse metrics where needed.
It would be cool to use in the admin panel.

**Comment by jipiboily** [comment]
Until (and if) this is supported, you could do it on your end by re-opening the `Prosperity::ApplicationController` and set the layout there to use the one from your main app. Would that work for you?

**Comment by accessd** [comment]
@jipiboily Not really. Still need to work main app url helpers, and ability to customize parent controller. And most important to use assets from gem in my layout. So I created pr.
